### ISSUE TITLE
Fitting via AD for integral-based models

### ISSUE THREAD

**Issue by rkurchin** [BattModels/ElectrochemicalKinetics.jl#3]
Zygote pretty much "just worked" on the non-integral models (once I figured out the syntax), so the fitting is using that now. However, it seems to stumble on QuadGK for the integral ones. Would be cool (and probably way faster) to do the fitting with gradients from Zygote rather than BlackBoxOptim...

**Comment by DhairyaLGandhi** [comment]
For anyone following, the branch `dg/ad` has the integral models working

**Comment by DhairyaLGandhi** [comment]
Close
